package communication;

public enum Operation {
    LOGIN,
    GET_ALL_ATHLETES,
    GET_ATHLETE_BY_PARAM,
    ADD_ATHLETE,
    UPDATE_ATHLETE,
    DELETE_ATHLETE,
    ADD_COMPETITION,
    GET_ALL_COMPETITIONS,
    GET_COMPETITION_BY_PARAM,
    UPDATE_COMPETITION,
    GET_ALL_DISCIPLINES,
    GET_DISCIPLINE_BY_COMPETITION,
    ADD_TIMETABLE,
    GET_ALL_TIMETABLES,
    GET_TIMETABLE_BY_PARAM,
    ADD_APPLICATION_FORM,
    GET_APPLICATION_FORM_BY_ATHLETE,
    GET_ALL_COMPETITION_TYPES
}
