package main.form;

import communication.Response;
import domain.Athlete;
import java.awt.Frame;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.controller.IController;
import main.tableModel.SearchAthleteTableModel;

public class SearchAthleteForm extends javax.swing.JDialog {

    private final Frame parent;
    private final IController controller;
    private List<Athlete> showedAthletes;

    /**
     * Creates new form SearchAthleteForm
     *
     * @param parent
     * @param modal
     * @param controller
     * @throws java.lang.Exception
     */
    public SearchAthleteForm(java.awt.Frame parent, boolean modal, IController controller) throws Exception {
        super(parent, modal);
        this.parent = parent;
        this.controller = controller;
        showedAthletes = new ArrayList<>();
        initComponents();
        loadAllCompetitions();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAthlete = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraživanje atletičara");

        btnSearch.setText("Pretraži");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblAthlete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAthlete);

        lblTitle.setText("Atletičari");

        lblSearch.setText("Unesite naziv države po kojoj želite da pretražite atletičare:");

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchParam = txtSearch.getText();
        Response response = controller.searchAthletes(searchParam);
        if (response.getException() != null) {
            if (response.getException() instanceof IOException) {
                showError("Sistem je pao.");
                dispose();
                parent.dispose();
                return;
            }
            showError(response.getException().getMessage());
            dispose();
            return;
        }
        showedAthletes = (List<Athlete>) response.getResult();
        if (showedAthletes.isEmpty()) {
            showError("Sistem ne može da nađe atletičare po zadatoj vrednosti");
        } else {
            showMessage("Sistem je našao atletičare po zadatoj vrednosti");
        }
        fillTable(showedAthletes);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selectedRow = tblAthlete.getSelectedRow();
        if (selectedRow == -1) {
            showError("Odaberite atletičara za koga želite da vidite podatke.");
            return;
        }
        Athlete athlete = makeAnAthlete(selectedRow);
        UpdateAthleteForm updateAthleteForm = new UpdateAthleteForm(parent, true, this, controller);
        updateAthleteForm.prepareView(athlete);
        updateAthleteForm.setVisible(true);

    }//GEN-LAST:event_btnDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAthlete;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void fillTable(List<Athlete> athletes) {
        SearchAthleteTableModel searchAthleteTableModel = new SearchAthleteTableModel(athletes);
        tblAthlete.setModel(searchAthleteTableModel);
    }

    private void loadAllCompetitions() throws Exception {
        Response response = controller.getAllAthletes();
        if (response.getException() != null) {
            throw response.getException();
        }
        showedAthletes = (List<Athlete>) response.getResult();
        if (showedAthletes.isEmpty()) {
            showMessage("Trenutno ne postoji ni jedan unet atletičar.");
            return;
        }
        fillTable(showedAthletes);
    }

    public void updateTable() {
        try {
            loadAllCompetitions();
        } catch (Exception ex) {
            Logger.getLogger(SearchAthleteForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Athlete makeAnAthlete(int selectedRow) {
        Athlete athlete = new Athlete();

        athlete.setId((int) tblAthlete.getValueAt(selectedRow, 0));
        athlete.setFirstname((String) tblAthlete.getValueAt(selectedRow, 1));
        athlete.setLastname((String) tblAthlete.getValueAt(selectedRow, 2));
        athlete.setBirthday((LocalDate) tblAthlete.getValueAt(selectedRow, 3));
        athlete.setState((String) tblAthlete.getValueAt(selectedRow, 4));

        return athlete;
    }

    private void showMessage(Object message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void showError(Object errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage, "Greška", JOptionPane.ERROR_MESSAGE);
    }
}
